export const PROFESSIONS = [
  "Accountant",
  "Actor",
  "Actuary",
  "Architect",
  "Artist",
  "Auditor",
  "Author",
  "Baker",
  "Banker",
  "Barber",
  "Barista",
  "Bartender",
  "Biologist",
  "Biomedical Engineer",
  "Blockchain Developer",
  "Business Analyst",
  "Chemist",
  "Chef",
  "Chiropractor",
  "Civil Engineer",
  "Coach",
  "Comedian",
  "Consultant",
  "Content Creator",
  "Copywriter",
  "Cybersecurity Analyst",
  "Data Analyst",
  "Data Scientist",
  "Dentist",
  "Designer",
  "Developer",
  "Dietitian",
  "Director",
  "DJ",
  "Doctor",
  "Driver",
  "Economist",
  "Editor",
  "Electrician",
  "Engineer",
  "Entrepreneur",
  "Event Planner",
  "Farmer",
  "Fashion Designer",
  "Filmmaker",
  "Financial Advisor",
  "Firefighter",
  "Fitness Trainer",
  "Flight Attendant",
  "Florist",
  "Founder",
  "Freelancer",
  "Game Developer",
  "Graphic Designer",
  "Hairdresser",
  "Historian",
  "HR Manager",
  "Illustrator",
  "Influencer",
  "Interior Designer",
  "Investment Banker",
  "Journalist",
  "Lawyer",
  "Librarian",
  "Makeup Artist",
  "Marketing Manager",
  "Massage Therapist",
  "Mechanic",
  "Mechanical Engineer",
  "Model",
  "Musician",
  "Nurse",
  "Nutritionist",
  "Paramedic",
  "Pharmacist",
  "Photographer",
  "Physician",
  "Physiotherapist",
  "Pilot",
  "Plumber",
  "Podcaster",
  "Police Officer",
  "Product Manager",
  "Professor",
  "Programmer",
  "Psychiatrist",
  "Psychologist",
  "Real Estate Agent",
  "Receptionist",
  "Recruiter",
  "Researcher",
  "Sales Representative",
  "Scientist",
  "SEO Specialist",
  "Social Media Manager",
  "Software Developer",
  "Software Engineer",
  "Student",
  "Surgeon",
  "Teacher",
  "Technician",
  "Therapist",
  "Tour Guide",
  "Translator",
  "UX/UI Designer",
  "Veterinarian",
  "Video Editor",
  "Videographer",
  "Waiter",
  "Writer",
  "Yoga Instructor"
].sort();
